### ISSUE TITLE
Implement Options

### ISSUE THREAD

**Issue by Zender54** [Zender54/VolumeReader#13]
Implement an extra JFrame to have various options including:
Edge detection threshold,
Maximum Minimum colouring variation

Need a reset to default option

**Comment by seam345** [comment]
this is gonna be one big ass project but i agree :)

**Comment by Zender54** [comment]
I think I can do this pretty easily in only one or two hours with just a simple extra menu.

**Comment by Zender54** [comment]
Being worked on in EdgeDetection branch.

**Comment by Zender54** [comment]
Done and merged into master
