### ISSUE TITLE
Add methods

### ISSUE THREAD

**Issue by Zender54** [Zender54/VolumeReader#8]
Add method for calculating max and min distance to axis in GLEventListener

**Comment by Zender54** [comment]
Lines 88 and 105 proceed code to be formed into method

**Comment by Zender54** [comment]
I would do this but I don't know what changes you have planned :/

**Comment by Zender54** [comment]
Being worked on in GLEventListener method.

**Comment by Zender54** [comment]
Finished and waiting for review before being merged.

**Comment by seam345** [comment]
what branch is it in ?

**Comment by Zender54** [comment]
GLEventListener

**Comment by Zender54** [comment]
Merged with master and done.
